# GitHub Actions Workflow configuration
# https://docs.github.com/actions/reference/workflow-syntax-for-github-actions
# https://github.com/actions/starter-workflows/blob/main/ci/dotnet-core.yml

name: .NET

# Note: on key treated as boolean key by YAML
# https://github.com/adrienverge/yamllint/issues/158#issuecomment-454313233
# However, GitHub Actions documentation is consistent in using it unquoted.
on:   # yamllint disable-line rule:truthy
- push
- pull_request

jobs:
  test:
    name: Test dotnet ${{ matrix.dotnet }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        # Uncomment to test on macOS:
        # - macos-latest
        - ubuntu-latest
        - windows-latest
        dotnet:
        # FIXME: Would prefer to test with latest SDK, or at least latest minor
        # version.  Not currently supported:
        # https://github.com/actions/setup-dotnet/issues/93
        # Poses problems for versions incompatible with worker image:
        # https://github.com/actions/setup-dotnet/issues/23#issuecomment-523554330
        # Note: Must quote value.  5.0 becomes 5, which silently fails.
        - '5.0'
        # Uncomment to test with an earlier SDK version:
        # - 3.1
    steps:
    - uses: actions/checkout@v2
    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Display .NET version
      run: dotnet --info
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: "dotnet test
        --configuration Release
        --no-restore
        --settings TestCoverage.runsettings
        "
    - name: Get path to lcov file
      id: get_lcov_path
      shell: bash
      run: |-
        printf '::set-output name=lcov_path::%s\n' \
          *.UnitTests/TestResults/*/coverage.info
    # Note: Codecov has poor support for matrix builds
    # https://github.com/codecov/codecov-action/issues/40
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
        file: ${{ steps.get_lcov_path.outputs.lcov_path }}
    - name: Upload coverage to Coveralls
      uses: coverallsapp/github-action@master
      with:
        flag-name: ${{ matrix.os }}_${{ matrix.dotnet }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel: true
        path-to-lcov: ${{ steps.get_lcov_path.outputs.lcov_path }}

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
